# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-10 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180310_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodscategorybrand',
            old_name='cagetor',
            new_name='category',
        ),
    ]
